Replace serde_cbor with serde_json
informalsystems/tendermint-rs pull request #1133
Opened 2022-05-25 15:12 UTC by devashishdxt

Fixes #1026.
Fixes #1038.

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Added entry in `.changelog/`

2022-05-26 08:07 UTC, xla requested changes
Bice, just a small nit.

2022-05-26 08:07 UTC, xla commented on light-client/Cargo.toml
> +serde_json = { version = "1.0.81", default-features = false, optional = true }
Dependencies are order alphanumerically.

2022-05-26 09:27 UTC, devashishdxt commented on light-client/Cargo.toml
> +serde_json = { version = "1.0.81", default-features = false, optional = true }
Done

2022-05-27 06:22 UTC, xla approved these changes
٩(˘◡˘)۶

2022-06-01 13:26 UTC, merged

2022-08-30 00:27 UTC, devashishdxt commented
@xla This PR was merged but I don't see these changes in `main` branch.

2022-09-01 18:40 UTC, thanethomson commented
`main` is effectively a fork off of tendermint-rs v0.23.x, since Tendermint Core v0.35/v0.36 were abandoned. See https://github.com/informalsystems/tendermint-rs/discussions/1179

This would need to be ported across to `main` again.