deps:  Use ed25519-consensus instead of ed25519-dalek (#1067)
informalsystems/tendermint-rs pull request #1245
Opened 2022-12-06 03:34 UTC by hdevalence

Backports this change to the new `main` (was #1067).

* Use ed25519-consensus instead of ed25519-dalek

Closes #355 (see that issue for more context; `ed25519-consensus` is a fork of `ed25519-zebra` that's Zcash-independent).

This change ensures that `tendermint-rs` has the same signature verification as `tendermint`, which uses the validation criteria provided by the Go `ed25519consensus` library.

* clippy fixes

Co-authored-by: Thane Thomson <connect@thanethomson.com>

* Remove redundant dependency

Signed-off-by: Thane Thomson <connect@thanethomson.com>

* cargo fmt

Signed-off-by: Thane Thomson <connect@thanethomson.com>

* Add changelog entries

Signed-off-by: Thane Thomson <connect@thanethomson.com>

Co-authored-by: Henry de Valence <hdevalence@penumbra.zone>

2022-12-08 09:36 UTC, mzabaluev requested changes
Generally looks good.

One thing which I find potentially problematic (though not a change I'm requesting now) is that ed25519-consensus does not integrate into the `signature` framework. Why is that?

2022-12-08 09:36 UTC, mzabaluev commented on p2p/src/error.rs
> -            [ DisplayOnly<SignatureError> ]
This error is deliberately opaque, but we can't make the `Display` impl transparent in flex-error, so we have our own message. OK.

2022-12-08 09:36 UTC, mzabaluev commented on p2p/src/secret_connection.rs
> -            proto::crypto::public_key::Sum::Secp256k1(_) => Err(Error::unsupported_key()),
I would rather keep the exhaustive match here, to force changes when new key types get added into protobuf.

Also, we're still working directly with proto, not through domain types. Not to be fixed in this PR, though.

2022-12-08 09:36 UTC, mzabaluev commented on tendermint/src/private_key.rs
> +    }
Great!

2022-12-08 09:36 UTC, mzabaluev commented on tendermint/src/public_key.rs
> +use signature::Verifier as _;
So with the "secp256k1" feature on, the trait's `verify` method is brought in scope, but our `VerificationKey` has the inherent `verify` method and it wins without ambiguity. Dodgy, but it works.

2022-12-08 09:36 UTC, mzabaluev commented on test/Cargo.toml
> +rand_core = { version = "0.6", default-features = false, features = ["std"] }
Huh, isis still has not updated their rand version? Another reason to switch.

2022-12-09 04:54 UTC, hdevalence commented
> Generally looks good.
> 
> One thing which I find potentially problematic (though not a change I'm requesting now) is that ed25519-consensus does not integrate into the `signature` framework. Why is that?

There's no particular reason; there wasn't a need to do it when the crate was written, and it wasn't possible to implement for trivial reasons -- AFAIR, it was because the `Signature` trait requires `AsRef<[u8]>`, but internally the `ed25519_consensus::Signature` type has two `[u8; 32]` arrays because that was slightly more convenient as an internal representation.

2022-12-09 10:35 UTC, mzabaluev commented
@hdevalence I think it's OK to not conform to the `signature` traits, as we're not going to make the Ed25519 implementation replaceable in the near term as per the previous discussion. The API is also close enough to not require significant rework if we decide we need it.

So, I think this just needs a change to do the exhaustive match for proto's key type enum, and we can merge it.

2022-12-09 14:36 UTC, tony-iqlusion commented
> AFAIR, it was because the Signature trait requires AsRef<[u8]>, but internally the ed25519_consensus::Signature type has two [u8; 32] arrays because that was slightly more convenient as an internal representation.

@hdevalence that bound is removed in a forthcoming `signature` v2.0 release, FWIW:

https://docs.rs/signature/2.0.0-pre.2/signature/index.html

2022-12-13 20:05 UTC, hdevalence commented
> @hdevalence I think it's OK to not conform to the `signature` traits, as we're not going to make the Ed25519 implementation replaceable in the near term as per discussion on Slack (recap: it's not supported by Web Crypto, corner cases addressed differently by other implementations so we need the precise behavior). The API is also close enough to not require significant rework if we decide we need it.
> 
> So, I think this just needs a change to do the exhaustive match for proto's key type enum, and we can merge it.

Cool, I updated the exhaustive match. I'd be happy to try to support the `signature` traits in a later release of the crate if it becomes relevant.

2022-12-15 12:57 UTC, mzabaluev approved these changes
Needs merging from main, but is otherwise good to go.

2022-12-15 18:07 UTC, hdevalence commented
Rebased.

2022-12-20 02:01 UTC, thanethomson commented
Was the failing check here due to clippy errors from Rust v1.66? If so, #1253's been merged and that should fix things.

2023-01-10 01:26 UTC, hdevalence commented
Rebased and did another round of clippy fixes.

2023-01-10 03:01 UTC, xla approved these changes
(͠≖ ͜ʖ͠≖)👌

2023-01-10 14:12 UTC, merged

2023-01-10 14:13 UTC, mzabaluev commented
Thank you @hdevalence and @xla!

2023-01-13 19:31 UTC, hdevalence commented
Thanks for merging this! Are there other changes in flight at the moment, or would it be possible to get it into a release soon?