tendermint-proto: grpc server definitions for rpc/abci
informalsystems/tendermint-rs pull request #1338
Opened 2023-07-24 22:16 UTC by erwanor

Addresses https://github.com/informalsystems/tendermint-rs/issues/1225, this PR adds gRPC server definitions for the rpc and abci services, but not (yet) for the privval service since it is blocked on #9256 for now.

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Added entry in `.changelog/`

2023-08-03 17:37 UTC, mzabaluev requested changes

2023-08-03 17:37 UTC, mzabaluev commented on proto/Cargo.toml
> +tonic = { version = "0.8", optional = true }
Please update to tonic 0.9. Hermes already uses that version.

2023-08-03 17:37 UTC, mzabaluev commented on proto/src/prost/v0_34/tendermint.rpc.grpc.rs
> +/// Generated server implementations.
If possible, avoid generating bindings for this package. It was removed from CometBFT as per https://github.com/cometbft/cometbft/issues/650

2023-08-03 17:37 UTC, mzabaluev commented on proto/Cargo.toml
> +grpc-client = ["tonic"]
As this feature is not used by generated code, perhaps let's not introduce it at this point.

2023-08-03 17:37 UTC, mzabaluev commented on proto/Cargo.toml
> +grpc = ["grpc-server", "grpc-client"]
Future-proofing for the eventual client bindings is good.

2023-08-03 22:22 UTC, erwanor commented
Thanks for the review @mzabaluev, I have bumped to `tonic@0.9`, removed the `grpc-client` feature, and modified the proto compiler to not generate bindings for the `rpc` server definitions.

However, I was not able to run the proto compiler as I previously did, so the PR has the old definitions:

```
⋊> ~/p/t/t/proto-compiler on tendermint-proto/grpc-server-traits ⨯ cargo run                                                                                                                                                                                                                                                                                                                                18:18:00
   Compiling tendermint-proto-compiler v0.3.0 (/Users/user/prod/tendermint-rs/tools/proto-compiler)
    Finished dev [unoptimized + debuginfo] target(s) in 0.88s
     Running `/Users/user/prod/tendermint-rs/tools/target/debug/tendermint-proto-compiler`
[info] => Fetching https://github.com/cometbft/cometbft at v0.34.28 into "/Users/user/prod/tendermint-rs/tools/proto-compiler/../target/tendermint"
  [info] => Cloning https://github.com/cometbft/cometbft into /Users/user/prod/tendermint-rs/tools/proto-compiler/../target/tendermint folder
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 2, message: "could not remove directory '/Users/user/prod/tendermint-rs/tools/target/tendermint/.git/refs/remotes/origin/pierre/fast-prototyping-1059': parent is not directory: Not a directory" }', proto-compiler/src/functions.rs:42:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2023-08-04 18:10 UTC, mzabaluev commented
@erwanor This looks like a weird problem with the git checkout. Try removing `target/tendermint` and running the compiler again.

2023-08-14 09:14 UTC, mzabaluev commented
> modified the proto compiler to not generate bindings for the `rpc` server definitions.

They are still generated, but I have slapped the `grpc-server` attribute on them. Let's leave it at that, generating everything is simpler.

2023-08-14 09:14 UTC, mzabaluev approved these changes

2023-08-14 15:12 UTC, erwanor commented
Thanks for your help with this, I owe you one!

2023-08-29 23:20 UTC, merged