rpc: Add HTTP timeout, default 30 seconds.
informalsystems/tendermint-rs pull request #1380
Opened 2023-11-14 19:01 UTC by mdyring

Simply introduces a HTTP timeout parameter, which is passed to reqwest.

This is highly desirable a the default behaviour is "no timeout", which can result in stalls.

Closes #1379.

* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Added entry in `.changelog/`

2024-02-19 09:24 UTC, mzabaluev requested changes
This looks good API-wise.
Can we follow the behavior in `reqwest` and have "no timeout" behavior by default? This will be also the least disruptive to the current users of `HttpClient`.

2024-03-04 13:38 UTC, rllola commented
Hey! We are looking forward for this to be merged because we have the issue of our request being stuck.

Anything we can do so it can be merged soon ?

2024-03-04 17:16 UTC, tony-iqlusion commented
Note that you can use e.g. `tokio::time::timeout` to enforce timeouts on anything `Future`-based without requiring upstream support.

That said, if you do end up adding this functionality in a first-class manner, I think it would also be good if it were on-by-default.

2024-03-05 20:37 UTC, mdyring commented
> This looks good API-wise. Can we follow the behavior in `reqwest` and have "no timeout" behavior by default? This will be also the least disruptive to the current users of `HttpClient`.

I'd argue that "no timeout" behavior is unexpected and thus not a good default (even though that seems to be the default for reqwest).

As @tony-iqlusion mentioned, `tokio::time::timeout` is also an option for library users, so alternatively it could simply be documented that the calls might hang.

2024-03-08 14:27 UTC, rllola commented
@tony-iqlusion Thanks for your solution.

I agree with @mdyring, the "no timeout" is unexpected and I am in favor of a default value around 30secs.

2024-03-13 17:54 UTC, tony-iqlusion commented
Personally I'm biased towards on-by-default timeouts, but having any sort of built-in timeout would be nice.

2024-03-13 19:47 UTC, romac commented
Alright, I'll rest my case then since you guys all agree that having a timeout by default is the preferred behaviour.

2024-03-13 19:47 UTC, romac approved these changes

2024-03-13 19:48 UTC, merged