Run Clippy on all targets (standard, tests, examples and benchmarks)
informalsystems/tendermint-rs pull request #554
Opened 2020-09-03 16:55 UTC by romac

Add the `--all-targets` flag to the invocation of Clippy in order to check all targets (standard, tests, examples and benchmarks).

---

Also renames the deprecated `--all` flag of `rustfmt` to `--workspace`.

---

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG.md

2020-09-03 22:48 UTC, greg-szabo requested changes
Apparently `cargo fmt` doesn't support `--workspace`. Weird, I also thought the change was consistent.

2020-09-03 23:19 UTC, greg-szabo approved these changes
I reverted the `--all` change for now.

I also fixed the clippy errors, they were annoying me in another PR too.

2020-09-03 23:19 UTC, merged

2020-09-04 08:00 UTC, romac commented
> Apparently `cargo fmt` doesn't support `--workspace`. Weird, I also thought the change was consistent.

Oh my bad, I mixed it up with `cargo build`, sorry about that and thanks for fixing the clippy errors :)

2020-09-04 08:02 UTC, romac commented on light-client/src/predicates/errors.rs
> +        matches!(self, Self::NotEnoughTrust { .. })
Good job Clippy :)