Allow testgen to be published to crates.io
informalsystems/tendermint-rs pull request #673
Opened 2020-11-12 15:56 UTC by thanethomson

`ibc-rs` is currently running into a dependency issue in https://github.com/informalsystems/ibc-rs/pull/390 due to the `tendermint-testgen` crate not being published on crates.io (see [`modules/Cargo.toml`](https://github.com/informalsystems/ibc-rs/blob/82476951668f4dc50006334ce1dbc1c13f0c719b/modules/Cargo.toml)).

We need to publish `tendermint-testgen` as a standalone crate to resolve this issue.

We don't have any crate documentation for testgen as of yet, but this can be remedied in a follow-up issue for the v0.17.0 release.

* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG.md

2020-11-12 18:56 UTC, greg-szabo reviewed
I think we should copy one of the READMEs from another crate so the preface will look nice on crates.io

2020-11-12 18:57 UTC, thanethomson commented
> I think we should copy one of the READMEs from another crate so the preface will look nice on crates.io

Sure - I can add that in quick.

2020-11-12 19:13 UTC, thanethomson commented
@greg-szabo: [rendered README](https://github.com/informalsystems/tendermint-rs/blob/testgen/publish/testgen/README.md)

I've also updated the crate docs with a small description.

2020-11-12 20:02 UTC, andrey-kuprianov requested changes
Thanks for taking care of this, @thanethomson @greg-szabo !

Besides minor changes everything looks fine to me.

2020-11-12 23:56 UTC, greg-szabo approved these changes
Love the README!

2020-11-13 08:47 UTC, andrey-kuprianov approved these changes
Looks good!

2020-11-13 08:48 UTC, merged