light-client: Replace `Io` with async variant
informalsystems/tendermint-rs pull request #995
Opened 2021-09-29 12:44 UTC by xla

Closes #953 
Supersedes #965

* [x] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [ ] ~~Wrote tests~~
* [ ] Added entry in `.changelog/`

2021-10-05 11:13 UTC, romac requested changes
Great stuff @xla! Left a few suggestions inline.

2021-10-05 11:13 UTC, romac commented on light-client/src/components/io.rs
> +use crate::utils::time::{timeout, TimeError};
Can we feature-guard this import so that it doesn't trigger an unused warning when building for wasm?

2021-10-05 11:13 UTC, romac commented on light-client/src/evidence.rs
> +use futures::future::FutureExt as _;
Can we feature-guard this import so that it doesn't trigger an unused warning when building for wasm?

2021-10-05 11:13 UTC, romac commented on light-client/src/evidence.rs
> +use crate::{components::io::IoError, types::PeerId, utils::time::timeout};
Can we feature-guard this import so that it doesn't trigger an unused warning when building for wasm?

2021-10-05 11:13 UTC, romac commented on light-client/src/evidence.rs
> +    #[async_trait::async_trait]
Can we import `async_trait::async_trait` and write this instead? It's a bit nicer on the eyes imho.

```suggestion
    #[async_trait]
```

2021-10-05 11:13 UTC, romac commented on light-client/src/fork_detector.rs
> +#[async_trait::async_trait]
```suggestion
#[async_trait]
```

2021-10-05 11:13 UTC, romac commented on light-client/src/supervisor.rs
> +    #[async_recursion::async_recursion]
```suggestion
    #[async_recursion]
```

2021-10-05 11:13 UTC, romac commented on light-client/src/tests.rs
> +#[async_trait::async_trait]
```suggestion
#[async_trait]
```

2021-10-05 11:13 UTC, romac commented on light-client/src/tests.rs
> +#[async_trait::async_trait]
```suggestion
#[async_trait]
```

2021-10-05 11:13 UTC, romac commented on light-client/src/utils/time.rs
> +pub async fn timeout<T>(duration: Duration, task: T) -> Result<T::Output, TimeError>
Can we feature-guard this when building for wasm?

2022-02-06 03:15 UTC, xla commented
<img width="594" alt="image" src="https://user-images.githubusercontent.com/1585/152666387-4069f077-ada8-44bf-8389-48686ce6ec51.png">

:<

2022-02-06 13:38 UTC, thanethomson commented
Welcome back @xla :slightly_smiling_face: 

CI was failing and there were multiple conflicts - please address those and I'll review.

2022-03-04 14:39 UTC, romac commented
@thanethomson  Can we re-open this and bring it across the finish line for the next major version of tendermint-rs (or the one after that)? Happy to help with that :)

2022-03-04 15:08 UTC, thanethomson commented
I'd be happy to reopen this, and @romac some help here would be greatly appreciated :slightly_smiling_face:

2022-04-08 05:57 UTC, xla commented
@romac @thanethomson Updated and fixed.

2022-04-09 11:04 UTC, thanethomson commented
Any ideas why the kvstore integration test keeps hanging and timing out?

2022-04-10 03:35 UTC, xla commented
> Any ideas why the kvstore integration test keeps hanging and timing out?

Addressed. You can't just go a little bit async and even worse trying to mix sync and async. The issue was that I naively was hoping to leave the supervisor handle untouched, but the crossbeam implementation when blocking on recv starves the current thread and therefore has a good chance of locking the async runtime.

@thanethomson The model based test fail for nightly, but I can't figure out why, any ideas?

2022-04-10 12:18 UTC, thanethomson commented
> The model based test fail for nightly, but I can't figure out why, any ideas?

Took another look through your code now and I can't see anything obvious contributing to the MBT failures, which means I'll need to spend a little more time digging. Will get back to you ASAP.

2022-04-11 11:40 UTC, thanethomson commented
I re-ran the nightly coverage test here and it passed, so it was nondeterministic :nauseated_face: Hopefully #1121 fixes that.

After merging #1120 it's unfortunately created a bunch of conflicts.

2022-04-11 12:14 UTC, xla commented
> I re-ran the nightly coverage test here and it passed, so it was nondeterministic 🤢 Hopefully #1121 fixes that.
> 
> After merging #1120 it's unfortunately created a bunch of conflicts.

Great, thanks for looking into it. Will resolve the conflicts.

2022-04-12 14:01 UTC, thanethomson approved these changes
I think this looks great, thanks @xla! :beers: 

TIL about `async_recursion`. It's sad that the compiler doesn't do this automatically - seems like the kind of thing that it should easily be able to detect and cater for without needing [workarounds](https://rust-lang.github.io/async-book/07_workarounds/04_recursion.html) or external crates.

2022-04-12 23:18 UTC, merged